self-hosted-runner:
  labels:
    - tdx

# Ignore attestations permission - actionlint doesn't recognize it yet but it's valid
# https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
ignore:
  - 'unknown permission scope .attestations.'
