use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct OpenApiDoc {
    components: Option<OpenApiComponents>,
}

#[derive(Debug, Deserialize)]
struct OpenApiComponents {
    schemas: BTreeMap<String, OpenApiSchema>,
}

#[derive(Debug, Deserialize)]
struct OpenApiSchema {
    #[serde(rename = "type")]
    schema_type: Option<String>,
    properties: Option<BTreeMap<String, OpenApiProperty>>,
    required: Option<Vec<String>>,
}

#[derive(Debug, Deserialize)]
struct OpenApiProperty {
    #[serde(rename = "type")]
    property_type: Option<String>,
    format: Option<String>,
    nullable: Option<bool>,
}

fn main() {
    let openapi_path = PathBuf::from("openapi/control-plane.yaml");
    println!("cargo:rerun-if-changed={}", openapi_path.display());

    let raw = fs::read_to_string(&openapi_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", openapi_path.display()));
    let doc: OpenApiDoc = serde_yaml::from_str(&raw)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", openapi_path.display()));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from openapi/control-plane.yaml\n");
    out.push_str("// Do not edit manually.\n\n");

    out.push_str(&emit_struct(&doc, "AgentChallengeResponse"));
    out.push('\n');
    out.push_str(&emit_struct(&doc, "AgentRegisterResponse"));

    let out_file = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("cp_client_api.rs");
    fs::write(&out_file, out)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_file.display()));
}

fn emit_struct(doc: &OpenApiDoc, schema_name: &str) -> String {
    let schema = doc
        .components
        .as_ref()
        .and_then(|components| components.schemas.get(schema_name))
        .unwrap_or_else(|| panic!("OpenAPI schema not found: {schema_name}"));

    if schema.schema_type.as_deref() != Some("object") {
        panic!("OpenAPI schema {schema_name} must be an object");
    }

    let properties = schema
        .properties
        .as_ref()
        .unwrap_or_else(|| panic!("OpenAPI schema {schema_name} must define properties"));
    let required: BTreeSet<&str> = schema
        .required
        .as_ref()
        .map(|fields| fields.iter().map(String::as_str).collect())
        .unwrap_or_default();

    let mut code = String::new();
    code.push_str("#[derive(Debug, Clone, serde::Deserialize, PartialEq)]\n");
    code.push_str(&format!("pub struct {schema_name} {{\n"));
    for (field_name, field_schema) in properties {
        let rust_type = rust_type_for_property(field_schema);
        let optional =
            field_schema.nullable.unwrap_or(false) || !required.contains(field_name.as_str());
        if optional {
            code.push_str("    #[serde(default)]\n");
            code.push_str(&format!("    pub {field_name}: Option<{rust_type}>,\n"));
        } else {
            code.push_str(&format!("    pub {field_name}: {rust_type},\n"));
        }
    }
    code.push_str("}\n");
    code
}

fn rust_type_for_property(prop: &OpenApiProperty) -> &'static str {
    match prop.property_type.as_deref() {
        Some("string") => match prop.format.as_deref() {
            Some("uuid") => "uuid::Uuid",
            _ => "String",
        },
        Some("integer") => match prop.format.as_deref() {
            Some("uint64") => "u64",
            _ => "i64",
        },
        Some("number") => "f64",
        Some("boolean") => "bool",
        Some(other) => panic!("unsupported OpenAPI property type: {other}"),
        None => panic!("OpenAPI property missing type"),
    }
}
