FROM rust:1-bookworm AS builder
RUN rustup target add x86_64-unknown-linux-musl && \
    apt-get update && \
    apt-get install -y --no-install-recommends musl-tools && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl --bin ee-smoke-admin

FROM scratch
COPY --from=builder /src/target/x86_64-unknown-linux-musl/release/ee-smoke-admin /ee-smoke-admin
EXPOSE 8080
ENTRYPOINT ["/ee-smoke-admin"]
