name: 'Register EasyEnclave App'
description: 'Register a new app with the EasyEnclave catalog'
author: 'EasyEnclave'

branding:
  icon: 'box'
  color: 'blue'

inputs:
  name:
    description: 'Unique app name'
    required: true
  description:
    description: 'App description'
    required: false
    default: ''
  source_repo:
    description: 'GitHub repo (e.g., org/repo). Defaults to current repo.'
    required: false
  maintainers:
    description: 'Comma-separated list of maintainer emails'
    required: false
    default: ''
  tags:
    description: 'Comma-separated list of tags'
    required: false
    default: ''
  control_plane_url:
    description: 'EasyEnclave control plane URL'
    required: false
    default: 'https://app.easyenclave.com'

outputs:
  app_id:
    description: 'The registered app ID'
    value: ${{ steps.register.outputs.app_id }}

runs:
  using: 'composite'
  steps:
    - name: Register app
      id: register
      shell: bash
      run: |
        set -euo pipefail

        # Build maintainers array
        MAINTAINERS_JSON="[]"
        if [ -n "${{ inputs.maintainers }}" ]; then
          MAINTAINERS_JSON=$(echo '${{ inputs.maintainers }}' | jq -R 'split(",") | map(ltrimstr(" ") | rtrimstr(" "))')
        fi

        # Build tags array
        TAGS_JSON="[]"
        if [ -n "${{ inputs.tags }}" ]; then
          TAGS_JSON=$(echo '${{ inputs.tags }}' | jq -R 'split(",") | map(ltrimstr(" ") | rtrimstr(" "))')
        fi

        # Default source_repo to current repo
        SOURCE_REPO="${{ inputs.source_repo }}"
        if [ -z "$SOURCE_REPO" ]; then
          SOURCE_REPO="${{ github.repository }}"
        fi

        is_json() { jq -e . >/dev/null 2>&1; }

        fetch_existing() {
          local tmp http_code body
          tmp="$(mktemp)"
          http_code="$(
            curl -sS -o "$tmp" -w "%{http_code}" \
              --connect-timeout 5 --max-time 20 --retry 3 --retry-delay 1 \
              "${{ inputs.control_plane_url }}/api/v1/apps/${{ inputs.name }}" || echo "000"
          )"
          body="$(cat "$tmp" 2>/dev/null || true)"
          rm -f "$tmp"
          printf '%s\n%s' "$http_code" "$body"
        }

        # Check if app already exists (idempotent)
        existing="$(fetch_existing)"
        existing_http="$(printf '%s\n' "$existing" | head -n1 || true)"
        existing_body="$(printf '%s\n' "$existing" | tail -n +2 || true)"
        if [ "$existing_http" = "200" ] && echo "$existing_body" | is_json; then
          if echo "$existing_body" | jq -e '.app_id' >/dev/null 2>&1; then
            APP_ID="$(echo "$existing_body" | jq -r '.app_id')"
            echo "App '${{ inputs.name }}' already registered ($APP_ID)"
            echo "app_id=$APP_ID" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        fi

        # Register the app
        REQUEST="$(jq -n \
          --arg name "${{ inputs.name }}" \
          --arg description "${{ inputs.description }}" \
          --arg source_repo "$SOURCE_REPO" \
          --argjson maintainers "$MAINTAINERS_JSON" \
          --argjson tags "$TAGS_JSON" \
          '{name: $name, description: $description, source_repo: $source_repo, maintainers: $maintainers, tags: $tags}')"

        tmp="$(mktemp)"
        http_code="$(
          curl -sS -o "$tmp" -w "%{http_code}" \
            --connect-timeout 5 --max-time 20 --retry 3 --retry-delay 1 \
            -X POST "${{ inputs.control_plane_url }}/api/v1/apps" \
            -H "Content-Type: application/json" \
            -d "$REQUEST" || echo "000"
        )"
        RESPONSE="$(cat "$tmp" 2>/dev/null || true)"
        rm -f "$tmp"

        if [ "$http_code" -ge 400 ]; then
          detail=""
          if echo "$RESPONSE" | is_json; then
            detail="$(echo "$RESPONSE" | jq -r '.detail // empty' 2>/dev/null || true)"
          fi
          if [ "$http_code" = "409" ] && echo "${detail:-}" | grep -qi "already"; then
            echo "::notice::App '${{ inputs.name }}' already exists (HTTP 409); fetching existing record"
            tmp2="$(mktemp)"
            code2="$(curl -sS -o "$tmp2" -w "%{http_code}" "${{ inputs.control_plane_url }}/api/v1/apps/${{ inputs.name }}" || echo "000")"
            RESPONSE="$(cat "$tmp2" 2>/dev/null || true)"
            rm -f "$tmp2"
            if [ "$code2" -ge 400 ] || ! echo "$RESPONSE" | is_json; then
              echo "::error::Failed to fetch existing app after conflict (HTTP $code2)."
              echo "Body (first 200 bytes):"
              echo "${RESPONSE:0:200}"
              exit 1
            fi
          else
            if [ -n "$detail" ]; then
              echo "::error::${detail}"
            else
              echo "::error::Register app failed (HTTP $http_code)."
              echo "Body (first 200 bytes):"
              echo "${RESPONSE:0:200}"
            fi
            exit 1
          fi
        fi

        if ! echo "$RESPONSE" | is_json; then
          echo "::error::Register app returned non-JSON (HTTP $http_code)."
          echo "Body (first 200 bytes):"
          echo "${RESPONSE:0:200}"
          exit 1
        fi

        APP_ID="$(echo "$RESPONSE" | jq -r '.app_id // empty')"
        if [ -z "$APP_ID" ] || [ "$APP_ID" = "null" ]; then
          echo "::error::Register app response missing app_id (HTTP $http_code)."
          echo "$RESPONSE" | jq .
          exit 1
        fi

        echo "app_id=$APP_ID" >> "$GITHUB_OUTPUT"
        echo "Registered app: ${{ inputs.name }} ($APP_ID)"
