"""add_github_oauth_fields

Revision ID: d22607323814
Revises: d73e399e0a31
Create Date: 2026-02-08 19:42:34.596530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd22607323814'
down_revision: Union[str, Sequence[str], None] = 'd73e399e0a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('github_login', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_org', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_api_key_prefix'), ['api_key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_github_id'), ['github_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=True)

    op.create_table('admin_sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('github_login', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_token_prefix'), ['token_prefix'], unique=False)

    op.create_table('transactions',
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('tx_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_type'), ['tx_type'], unique=False)

    op.drop_table('trusted_mrtds')
    op.drop_table('workers')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_queue_order'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtmrs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('sla_tiers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('machine_sizes', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agents_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingress', sa.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_app_versions_app_name_version'), type_='unique')

    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('sla_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('machine_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('cpu_vcpus', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('memory_gb', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('gpu_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_charge_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_charged', sa.Float(), nullable=False))
        batch_op.create_index(batch_op.f('ix_deployments_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_account_id'))
        batch_op.drop_column('total_charged')
        batch_op.drop_column('last_charge_time')
        batch_op.drop_column('gpu_count')
        batch_op.drop_column('memory_gb')
        batch_op.drop_column('cpu_vcpus')
        batch_op.drop_column('machine_size')
        batch_op.drop_column('sla_class')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_app_versions_app_name_version'), ['app_name', 'version'])
        batch_op.drop_column('ingress')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_account_id'))
        batch_op.drop_column('machine_sizes')
        batch_op.drop_column('sla_tiers')
        batch_op.drop_column('account_id')
        batch_op.drop_column('rtmrs')

    op.create_table('jobs',
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('compose', sa.VARCHAR(), nullable=False),
    sa.Column('build_context', sqlite.JSON(), nullable=True),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('worker_id', sa.VARCHAR(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('attestation', sqlite.JSON(), nullable=True),
    sa.Column('service_id', sa.VARCHAR(), nullable=True),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('queue_order', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_queue_order'), ['queue_order'], unique=False)

    op.create_table('workers',
    sa.Column('worker_id', sa.VARCHAR(), nullable=False),
    sa.Column('attestation', sqlite.JSON(), nullable=True),
    sa.Column('capabilities', sqlite.JSON(), nullable=True),
    sa.Column('registered_at', sa.DATETIME(), nullable=False),
    sa.Column('last_heartbeat', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('current_job_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('trusted_mrtds',
    sa.Column('mrtd', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('locked', sa.BOOLEAN(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('image_version', sa.VARCHAR(), nullable=False),
    sa.Column('source_repo', sa.VARCHAR(), nullable=True),
    sa.Column('source_commit', sa.VARCHAR(), nullable=True),
    sa.Column('source_tag', sa.VARCHAR(), nullable=True),
    sa.Column('build_workflow', sa.VARCHAR(), nullable=True),
    sa.Column('image_digest', sa.VARCHAR(), nullable=True),
    sa.Column('attestation_url', sa.VARCHAR(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=False),
    sa.Column('added_by', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('mrtd')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_tx_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_token_prefix'))

    op.drop_table('admin_sessions')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_github_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_api_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
