"""Initial schema

Revision ID: d73e399e0a31
Revises: 
Create Date: 2026-02-04 17:19:27.343113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd73e399e0a31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vm_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attestation', sa.JSON(), nullable=True),
    sa.Column('mrtd', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intel_ta_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tunnel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tunnel_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_deployment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('health_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('unhealthy_since', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tunnel_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_attestation_check', sa.DateTime(), nullable=True),
    sa.Column('attestation_valid', sa.Boolean(), nullable=False),
    sa.Column('attestation_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_verified'), ['verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_vm_name'), ['vm_name'], unique=True)

    op.create_table('app_versions',
    sa.Column('version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mrtd', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attestation', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_versions_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_versions_status'), ['status'], unique=False)
        batch_op.create_unique_constraint('uq_app_versions_app_name_version', ['app_name', 'version'])

    op.create_table('apps',
    sa.Column('app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('maintainers', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apps_name'), ['name'], unique=True)

    op.create_table('deployments',
    sa.Column('deployment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('build_context', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attestation', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('build_context', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('attestation', sa.JSON(), nullable=True),
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queue_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_queue_order'), ['queue_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('services',
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compose_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoints', sa.JSON(), nullable=True),
    sa.Column('mrtd', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attestation_json', sa.JSON(), nullable=True),
    sa.Column('intel_ta_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('health_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_health_status'), ['health_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=True)

    op.create_table('trusted_mrtds',
    sa.Column('mrtd', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('build_workflow', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attestation_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('mrtd')
    )
    op.create_table('workers',
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attestation', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    op.drop_table('trusted_mrtds')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_name'))
        batch_op.drop_index(batch_op.f('ix_services_health_status'))

    op.drop_table('services')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_queue_order'))

    op.drop_table('jobs')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_status'))
        batch_op.drop_index(batch_op.f('ix_deployments_agent_id'))

    op.drop_table('deployments')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_name'))

    op.drop_table('apps')
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_app_versions_app_name_version', type_='unique')
        batch_op.drop_index(batch_op.f('ix_app_versions_status'))
        batch_op.drop_index(batch_op.f('ix_app_versions_app_name'))

    op.drop_table('app_versions')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_vm_name'))
        batch_op.drop_index(batch_op.f('ix_agents_verified'))
        batch_op.drop_index(batch_op.f('ix_agents_status'))

    op.drop_table('agents')
    # ### end Alembic commands ###
