name: Preflight - GCP capacity
description: Ensure at least one healthy verified GCP agent exists by requesting billed capacity via the control plane

inputs:
  control_plane_url:
    description: EasyEnclave control plane URL
    required: false
    default: "https://app.easyenclave.com"
  node_size:
    description: Agent node_size to provision (e.g. tiny)
    required: false
    default: "tiny"
  wait_seconds:
    description: Seconds to wait for agent registration
    required: false
    default: "900"

  # Billing-backed capacity request credentials.
  billing_account_id:
    description: Billing deployer account_id used for capacity purchases
    required: false
    default: ""
  billing_api_key:
    description: Billing account API key (Authorization Bearer)
    required: false
    default: ""
  billing_months:
    description: Number of months to purchase for requested warm capacity
    required: false
    default: "1"

  # Deprecated admin inputs retained for compatibility (ignored).
  cp_admin_token:
    description: Deprecated (ignored)
    required: false
    default: ""
  cp_admin_password:
    description: Deprecated (ignored)
    required: false
    default: ""

  # Preferred CP dispatch target. If empty, first entry from gcp_zone is used.
  gcp_datacenter:
    description: Datacenter label to request from control plane (e.g. gcp:us-central1-a)
    required: false
    default: ""

  # Deprecated legacy inputs retained for compatibility with existing workflow callers.
  gcp_project_id:
    description: Deprecated (ignored)
    required: false
    default: ""
  gcp_wif_provider:
    description: Deprecated (ignored)
    required: false
    default: ""
  gcp_wif_service_account:
    description: Deprecated (ignored)
    required: false
    default: ""
  gcp_service_account_key:
    description: Deprecated (ignored)
    required: false
    default: ""
  gcp_zone:
    description: Comma-separated zones; first entry is used as default dispatch target
    required: false
    default: "us-central1-a,us-central1-b,us-central1-c,us-central1-f,us-east4-a,us-west1-b"
  gcp_region:
    description: Deprecated (ignored)
    required: false
    default: ""
  gcp_machine_type:
    description: Deprecated (ignored)
    required: false
    default: ""
  gcp_boot_disk_size:
    description: Deprecated (ignored)
    required: false
    default: ""

outputs:
  gcp_eligible_agents:
    description: Count of eligible verified healthy GCP agents after preflight
    value: ${{ steps.final.outputs.gcp_eligible_agents }}
  gcp_provisioned:
    description: Whether the action attempted provisioning (true/false)
    value: ${{ steps.final.outputs.gcp_provisioned }}

runs:
  using: composite
  steps:
    - name: Validate billing capacity credentials
      shell: bash
      env:
        BILLING_ACCOUNT_ID: ${{ inputs.billing_account_id }}
        BILLING_API_KEY: ${{ inputs.billing_api_key }}
        CP_ADMIN_TOKEN: ${{ inputs.cp_admin_token }}
        CP_ADMIN_PASSWORD: ${{ inputs.cp_admin_password }}
      run: |
        set -euo pipefail
        if [ -n "${CP_ADMIN_TOKEN:-}" ] || [ -n "${CP_ADMIN_PASSWORD:-}" ]; then
          echo "::warning::cp_admin_token/cp_admin_password are deprecated and ignored by preflight-gcp."
        fi
        if [ -z "${BILLING_ACCOUNT_ID:-}" ]; then
          echo "::error::Missing billing_account_id. Configure a deployer billing account for capacity requests."
          exit 1
        fi
        if [ -z "${BILLING_API_KEY:-}" ]; then
          echo "::error::Missing billing_api_key. Configure a deployer billing API key for capacity requests."
          exit 1
        fi

    - name: Precheck - healthy verified GCP agents
      id: precheck
      shell: bash
      env:
        CP_URL: ${{ inputs.control_plane_url }}
        NODE_SIZE: ${{ inputs.node_size }}
      run: |
        set -euo pipefail
        agents="$(curl -sSf -H 'Accept: application/json' "$CP_URL/api/v1/agents")"
        count="$(
          echo "${agents:-}" | jq --arg ns "${NODE_SIZE:-}" '
            [.agents[]
              | (.datacenter // "" | ascii_downcase) as $dc
              | (.status // "" | ascii_downcase) as $st
              | select(.verified == true
                and (.health_status // "" | ascii_downcase) == "healthy"
                and (if ($ns | length) > 0 then ((.node_size // "" | ascii_downcase) == ($ns | ascii_downcase)) else true end)
                and ($st == "undeployed" or ($st == "deployed" and ((.deployed_app // "") | test("^measuring-enclave") | not)))
                and ($dc | startswith("gcp:") or $dc == "gcp"))
            ] | length
          ' 2>/dev/null || echo 0
        )"

        echo "gcp_eligible_agents=$count" >> "$GITHUB_OUTPUT"

        if [ "$count" -gt 0 ]; then
          echo "Found $count eligible GCP agents."
          echo "need_provision=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "need_provision=true" >> "$GITHUB_OUTPUT"
        echo "::warning::No healthy verified GCP agents available; requesting control-plane capacity dispatch."

    - name: Request control-plane GCP capacity dispatch
      if: steps.precheck.outputs.need_provision == 'true'
      id: dispatch
      shell: bash
      env:
        CP_URL: ${{ inputs.control_plane_url }}
        BILLING_ACCOUNT_ID: ${{ inputs.billing_account_id }}
        BILLING_API_KEY: ${{ inputs.billing_api_key }}
        BILLING_MONTHS: ${{ inputs.billing_months }}
        NODE_SIZE: ${{ inputs.node_size }}
        GCP_DATACENTER: ${{ inputs.gcp_datacenter }}
        GCP_ZONE: ${{ inputs.gcp_zone }}
      run: |
        set -euo pipefail
        if [ -z "${BILLING_ACCOUNT_ID:-}" ] || [ -z "${BILLING_API_KEY:-}" ]; then
          echo "::error::Missing billing credentials for capacity purchase."
          exit 1
        fi
        if ! echo "${BILLING_MONTHS:-1}" | grep -Eq '^[1-9][0-9]*$'; then
          echo "::error::Invalid billing_months='${BILLING_MONTHS:-}'. Expected integer >= 1."
          exit 1
        fi

        target_dc="$(echo "${GCP_DATACENTER:-}" | tr '[:upper:]' '[:lower:]' | xargs)"
        if [ -z "$target_dc" ]; then
          first_zone="$(echo "${GCP_ZONE:-}" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed '/^$/d' | head -n1)"
          first_zone="$(echo "$first_zone" | tr '[:upper:]' '[:lower:]')"
          if [ -n "$first_zone" ]; then
            case "$first_zone" in
              gcp:*)
                target_dc="$first_zone"
                ;;
              *)
                target_dc="gcp:$first_zone"
                ;;
            esac
          else
            target_dc="gcp"
          fi
        fi

        payload="$(jq -cn \
          --arg dc "$target_dc" \
          --arg ns "${NODE_SIZE:-}" \
          --argjson months "${BILLING_MONTHS:-1}" \
          --arg reason "deploy-example-gcp-preflight-${GITHUB_RUN_ID:-local}-${GITHUB_RUN_ATTEMPT:-1}" \
          '{
            datacenter: $dc,
            node_size: $ns,
            min_warm_count: 1,
            months: $months,
            reason: $reason
          }'
        )"

        body="$(mktemp)"
        http_code="$(
          curl -sS -o "$body" -w "%{http_code}" \
            -X POST "$CP_URL/api/v1/accounts/${BILLING_ACCOUNT_ID}/capacity/request" \
            -H "Authorization: Bearer ${BILLING_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "$payload" || echo 000
        )"
        resp="$(cat "$body")"
        rm -f "$body"

        if [ "$http_code" -ge 400 ]; then
          detail="$(echo "$resp" | jq -r '.detail // empty' 2>/dev/null || true)"
          echo "::error::Control-plane dispatch request failed (HTTP $http_code): ${detail:-$resp}"
          exit 1
        fi

        shortfall="$(echo "$resp" | jq -r '.capacity.targets[0].shortfall // 0' 2>/dev/null || echo 0)"
        dispatched="$(echo "$resp" | jq -r '.capacity.dispatches[0].dispatched // false' 2>/dev/null || echo false)"
        detail="$(echo "$resp" | jq -r '.capacity.dispatches[0].detail // empty' 2>/dev/null || true)"
        status_code="$(echo "$resp" | jq -r '.capacity.dispatches[0].status_code // empty' 2>/dev/null || true)"
        tx_id="$(echo "$resp" | jq -r '.transaction_id // empty' 2>/dev/null || true)"
        charged="$(echo "$resp" | jq -r '.charged_amount_usd // 0' 2>/dev/null || echo 0)"
        simulated="$(echo "$resp" | jq -r '.simulated_payment // false' 2>/dev/null || echo false)"

        echo "target_datacenter=$target_dc" >> "$GITHUB_OUTPUT"
        echo "provisioned=$dispatched" >> "$GITHUB_OUTPUT"
        if [ -n "$tx_id" ]; then
          echo "transaction_id=$tx_id" >> "$GITHUB_OUTPUT"
        fi

        if [ "${shortfall:-0}" -gt 0 ] && [ "$dispatched" != "true" ]; then
          echo "::error::Control plane reported shortfall=$shortfall but did not dispatch provisioning."
          if [ -n "$detail" ]; then
            echo "::error::$detail"
          fi
          if [ -n "$status_code" ]; then
            echo "::error::Dispatch status_code=$status_code"
          fi
          exit 1
        fi

        echo "Capacity request accepted: datacenter='$target_dc' node_size='${NODE_SIZE:-}' shortfall=$shortfall dispatched=$dispatched tx_id=${tx_id:-none} charged=${charged} simulated=${simulated}"

    - name: Wait for eligible GCP capacity after dispatch
      if: steps.precheck.outputs.need_provision == 'true'
      shell: bash
      env:
        CP_URL: ${{ inputs.control_plane_url }}
        NODE_SIZE: ${{ inputs.node_size }}
        WAIT_SECONDS: ${{ inputs.wait_seconds }}
      run: |
        set -euo pipefail

        deadline=$(( $(date +%s) + ${WAIT_SECONDS:-900} ))
        while :; do
          agents="$(curl -sSf -H 'Accept: application/json' "$CP_URL/api/v1/agents")"
          count="$(
            echo "${agents:-}" | jq --arg ns "${NODE_SIZE:-}" '
              [.agents[]
                | (.datacenter // "" | ascii_downcase) as $dc
                | (.status // "" | ascii_downcase) as $st
                | select(.verified == true
                  and (.health_status // "" | ascii_downcase) == "healthy"
                  and (if ($ns | length) > 0 then ((.node_size // "" | ascii_downcase) == ($ns | ascii_downcase)) else true end)
                  and ($st == "undeployed" or ($st == "deployed" and ((.deployed_app // "") | test("^measuring-enclave") | not)))
                  and ($dc | startswith("gcp:") or $dc == "gcp"))
              ] | length
            ' 2>/dev/null || echo 0
          )"
          if [ "$count" -gt 0 ]; then
            echo "Eligible GCP capacity is now available: $count"
            exit 0
          fi
          now="$(date +%s)"
          if [ "$now" -ge "$deadline" ]; then
            echo "::error::Timed out waiting for eligible GCP capacity after dispatch."
            exit 1
          fi
          sleep 10
        done

    - name: Final check - healthy verified GCP agents
      id: final
      shell: bash
      env:
        CP_URL: ${{ inputs.control_plane_url }}
        NODE_SIZE: ${{ inputs.node_size }}
        PROVISIONED: ${{ steps.dispatch.outputs.provisioned }}
      run: |
        set -euo pipefail
        agents="$(curl -sSf -H 'Accept: application/json' "$CP_URL/api/v1/agents")"
        count="$(
          echo "${agents:-}" | jq --arg ns "${NODE_SIZE:-}" '
            [.agents[]
              | (.datacenter // "" | ascii_downcase) as $dc
              | (.status // "" | ascii_downcase) as $st
              | select(.verified == true
                and (.health_status // "" | ascii_downcase) == "healthy"
                and (if ($ns | length) > 0 then ((.node_size // "" | ascii_downcase) == ($ns | ascii_downcase)) else true end)
                and ($st == "undeployed" or ($st == "deployed" and ((.deployed_app // "") | test("^measuring-enclave") | not)))
                and ($dc | startswith("gcp:") or $dc == "gcp"))
            ] | length
          ' 2>/dev/null || echo 0
        )"

        echo "gcp_eligible_agents=$count" >> "$GITHUB_OUTPUT"
        provisioned="${PROVISIONED:-false}"
        if [ -z "$provisioned" ]; then
          provisioned="false"
        fi
        echo "gcp_provisioned=$provisioned" >> "$GITHUB_OUTPUT"

        if [ "$count" -le 0 ]; then
          echo "::error::No eligible verified GCP agents available."
          echo "::error::Control-plane dispatch either failed or no provisioner fulfilled the request."
          exit 1
        fi
        echo "Found $count eligible verified GCP agents."
